background_opacity 0.8

copy_on_select yes
clipboard_control write-clipboard write-primary read-clipboard read-primary
map ctrl+shift+v paste_from_clipboard
map ctrl+shift+c copy_to_clipboard

map ctrl+plus   change_font_size all +1.0
map ctrl+minus  change_font_size all -1.0
